name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to publish (i.e. v1.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        version_string=${${{ inputs.version }}#"v"}
        version_parts=$(echo $version_string | tr "." "\n")
        for v_part in $version_parts
        do
            echo "> [$v_part]"
        done
