on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          jsonnet-dir: ./testdata/
          generated-dir: ./testdata/generated/
