name: Self Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          jsonnet-dir: ./testdata/
          generated-dir: ./testdata/generated/
      - uses: ./
        with:
          jsonnet-dir: ./testdata/
          generated-dir: ./testdata/generated/
          convert-to-yaml: true
